name: Build
on:
  pull_request:
    paths:
      - .github/workflows/build.yml
      - Dockerfile
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - Dockerfile
    tags:
      - 'v*'
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/dnsmasq
          tags: |
            type=edge,branch=master
            type=ref,event=pr
            type=ref,event=tag
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/386, linux/amd64, linux/arm/v5, linux/arm/v7, linux/arm64/v8, linux/mips64le, linux/ppc64le, linux/s390x
          push: true
          tags: ${{ steps.meta.outputs.tags }}